/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#e1fdff",
        "primary-container": "#00f2ff",
        "primary-fixed": "#74f5ff",
        "primary-fixed-dim": "#00dbe7",
        "on-primary": "#00363a",
        "on-primary-container": "#006a71",
        "on-primary-fixed": "#002022",
        "on-primary-fixed-variant": "#004f54",
        "inverse-primary": "#00696f",

        "secondary": "#a6e6ff",
        "secondary-container": "#14d1ff",
        "secondary-fixed": "#b7eaff",
        "secondary-fixed-dim": "#4cd6ff",
        "on-secondary": "#003543",
        "on-secondary-container": "#00566b",
        "on-secondary-fixed": "#001f28",
        "on-secondary-fixed-variant": "#004e60",

        "tertiary": "#fff6e4",
        "tertiary-container": "#fed83a",
        "tertiary-fixed": "#ffe173",
        "tertiary-fixed-dim": "#e8c423",
        "on-tertiary": "#3b2f00",
        "on-tertiary-container": "#725e00",
        "on-tertiary-fixed": "#221b00",
        "on-tertiary-fixed-variant": "#554500",

        "background": "#0d1515",
        "on-background": "#dce4e4",
        "surface": "#0d1515",
        "surface-dim": "#0d1515",
        "surface-bright": "#333b3b",
        "surface-variant": "#2e3637",
        "surface-tint": "#00dbe7",
        "surface-container-lowest": "#080f10",
        "surface-container-low": "#151d1e",
        "surface-container": "#192122",
        "surface-container-high": "#232b2c",
        "surface-container-highest": "#2e3637",
        "on-surface": "#dce4e4",
        "on-surface-variant": "#b9cacb",
        "inverse-surface": "#dce4e4",
        "inverse-on-surface": "#2a3232",

        "outline": "#849495",
        "outline-variant": "#3a494b",

        "error": "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",

        "layer-0": "#0A0C10",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        "3xl": "1rem",
      },
      spacing: {
        "container-max": "1280px",
        "margin-desktop": "64px",
        "margin-mobile": "16px",
        "gutter": "24px",
        "unit": "8px",
      },
      fontFamily: {
        "display": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-main": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "button-text": ["14px", { lineHeight: "1", fontWeight: "600" }],
        "data-label": ["12px", { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "500" }],
      },
      animation: {
        'scan': 'scan 3s ease-in-out infinite',
        'float': 'float 10s infinite linear',
        'pulse-glow': 'pulseGlow 2s ease-in-out infinite',
      },
      keyframes: {
        scan: {
          '0%': { top: '0%', opacity: '0' },
          '10%': { opacity: '0.8' },
          '90%': { opacity: '0.8' },
          '100%': { top: '100%', opacity: '0' },
        },
        float: {
          '0%': { transform: 'translateY(100vh) translateX(0)', opacity: '0' },
          '10%': { opacity: '0.5' },
          '90%': { opacity: '0.5' },
          '100%': { transform: 'translateY(-100px) translateX(20px)', opacity: '0' },
        },
        pulseGlow: {
          '0%, 100%': { boxShadow: '0 0 8px rgba(0,219,231,0.4)' },
          '50%': { boxShadow: '0 0 20px rgba(0,219,231,0.8)' },
        },
      },
    },
  },
  plugins: [],
}
